/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ConvertersRouteImport } from './routes/converters'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CCategoryRouteImport } from './routes/c.$category'
import { Route as CCategoryIndexRouteImport } from './routes/c.$category.index'
import { Route as CCategoryPairRouteImport } from './routes/c.$category.$pair'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertersRoute = ConvertersRouteImport.update({
  id: '/converters',
  path: '/converters',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CCategoryRoute = CCategoryRouteImport.update({
  id: '/c/$category',
  path: '/c/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const CCategoryIndexRoute = CCategoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CCategoryRoute,
} as any)
const CCategoryPairRoute = CCategoryPairRouteImport.update({
  id: '/$pair',
  path: '/$pair',
  getParentRoute: () => CCategoryRoute,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/converters': typeof ConvertersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/c/$category': typeof CCategoryRouteWithChildren
  '/api/public/contact': typeof ApiPublicContactRoute
  '/c/$category/$pair': typeof CCategoryPairRoute
  '/c/$category/': typeof CCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/converters': typeof ConvertersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/c/$category/$pair': typeof CCategoryPairRoute
  '/c/$category': typeof CCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/converters': typeof ConvertersRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/c/$category': typeof CCategoryRouteWithChildren
  '/api/public/contact': typeof ApiPublicContactRoute
  '/c/$category/$pair': typeof CCategoryPairRoute
  '/c/$category/': typeof CCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/converters'
    | '/sitemap.xml'
    | '/c/$category'
    | '/api/public/contact'
    | '/c/$category/$pair'
    | '/c/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/converters'
    | '/sitemap.xml'
    | '/api/public/contact'
    | '/c/$category/$pair'
    | '/c/$category'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/converters'
    | '/sitemap.xml'
    | '/c/$category'
    | '/api/public/contact'
    | '/c/$category/$pair'
    | '/c/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  ConvertersRoute: typeof ConvertersRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CCategoryRoute: typeof CCategoryRouteWithChildren
  ApiPublicContactRoute: typeof ApiPublicContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/converters': {
      id: '/converters'
      path: '/converters'
      fullPath: '/converters'
      preLoaderRoute: typeof ConvertersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$category': {
      id: '/c/$category'
      path: '/c/$category'
      fullPath: '/c/$category'
      preLoaderRoute: typeof CCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$category/': {
      id: '/c/$category/'
      path: '/'
      fullPath: '/c/$category/'
      preLoaderRoute: typeof CCategoryIndexRouteImport
      parentRoute: typeof CCategoryRoute
    }
    '/c/$category/$pair': {
      id: '/c/$category/$pair'
      path: '/$pair'
      fullPath: '/c/$category/$pair'
      preLoaderRoute: typeof CCategoryPairRouteImport
      parentRoute: typeof CCategoryRoute
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CCategoryRouteChildren {
  CCategoryPairRoute: typeof CCategoryPairRoute
  CCategoryIndexRoute: typeof CCategoryIndexRoute
}

const CCategoryRouteChildren: CCategoryRouteChildren = {
  CCategoryPairRoute: CCategoryPairRoute,
  CCategoryIndexRoute: CCategoryIndexRoute,
}

const CCategoryRouteWithChildren = CCategoryRoute._addFileChildren(
  CCategoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  ConvertersRoute: ConvertersRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CCategoryRoute: CCategoryRouteWithChildren,
  ApiPublicContactRoute: ApiPublicContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
